/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Jul 25 21:01:39 2019. */

#include "LightControl.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t LightControl_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, LightControl, control, control, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
