/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Jul 25 21:01:39 2019. */

#ifndef PB_LIGHTCONTROL_PB_H_INCLUDED
#define PB_LIGHTCONTROL_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _LightControl {
    int32_t control;
/* @@protoc_insertion_point(struct:LightControl) */
} LightControl;

/* Default values for struct fields */

/* Initializer values for message structs */
#define LightControl_init_default                {0}
#define LightControl_init_zero                   {0}

/* Field tags (for use in manual encoding/decoding) */
#define LightControl_control_tag                 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t LightControl_fields[2];

/* Maximum encoded size of messages (where known) */
#define LightControl_size                        11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define LIGHTCONTROL_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
